name: Running Code Coverage

on: 
  pull_request:
  push:
    branches:
      - devel
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    
    - name: Run the tests
      run: npm test -- --coverage
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_API }}
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
